config/routes.rb
Rails.application.routes.draw do
  
    root "users#home"

  	get    '/help',    to: 'static_pages#help'
 	get    '/about',   to: 'static_pages#about'
  	get    '/contact', to: 'static_pages#contact'
 	get    '/signup',  to: 'users#new'
 	get    '/login',   to: 'sessions#new'
 	post   '/login',   to: 'sessions#create'
  	delete '/logout',  to: 'sessions#destroy'



  resources :users

end

#   Prefix Verb   URI Pattern               Controller#Action
#     root GET    /                         users#home
#     help GET    /help(.:format)           static_pages#help
#    about GET    /about(.:format)          static_pages#about
#  contact GET    /contact(.:format)        static_pages#contact
#   signup GET    /signup(.:format)         users#new
#    login GET    /login(.:format)          sessions#new
#          POST   /login(.:format)          sessions#create
#   logout DELETE /logout(.:format)         sessions#destroy
#    users GET    /users(.:format)          users#index
#          POST   /users(.:format)          users#create
# new_user GET    /users/new(.:format)      users#new
#edit_user GET    /users/:id/edit(.:format) users#edit
#     user GET    /users/:id(.:format)      users#show
#          PATCH  /users/:id(.:format)      users#update
#          PUT    /users/:id(.:format)      users#update
#          DELETE /users/:id(.:format)      users#destroy
#     users#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages.rb
class Static_pagesController < ApplicationController
	def help		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @titre = "Inscription"
  end

  def show
    @users = User.find(params[:id])
  end

  def create
    @users = User.create(users_params)
    if @users.save
      log_in @users
      flash[:success] = "Bienvenu vers une totale pensée cosmique vers un nouvel age réminiscent"
      redirect_to @users
    else 
      render 'new'
    end
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])
    if @users.update(params.require(:users).permit(:email))
       redirect_to @users
    else
      render 'new'
    end
  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy
    redirect_to users_path
  end

  private

  def users_params
      params.require(:user).permit(:email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
            <li><a href="http://op-spe-cdn.20mn.fr/magazine/wp-content/uploads/sites/78/2014/12/bebe-crise-de-nerf-645x400.jpg">A bout</a></li>
      <li><a href="https://www.youtube.com/watch?v=cUdcEkO7ro0">Contact</a></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Secret</title>
    <%= csrf_meta_tags %>    

  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Log out", root_path, method: :delete %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>Franchemetn, faut que tu mettes les mains dans le combouïs</h1>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/home.html.erb
 <div class="center jumbotron">
  <h1>Bienvenu sur le site de Skippy</h1>
  <h3>
    Sur ce site tu peux trouver une totale liberté de pensée cosmique vers un nouvel âge reminiscent!
  </h3>
  <%= link_to 'Connecte toi', login_path, class: "btn btn-lg btn-primary" %>

  <%= link_to 'Enregistre toi', signup_path, class: "btn btn-lg btn-primary" %><br><br>

  <h5>"Tout bien que tu detiens est un souci qui te retiens et Skippy est la pour nous hoter tout nos soucis..."</h5>
</div>

app/views/users/index.html.erb
<h1>Circuler , ya rien à voir</h1>
<p><%= @users.all %></p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>

  <div class="form-group">

    <label>Email</label>

    <%= f.text_field :email, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Password</label>

    <%= f.password_field :password, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Confirm Password</label>

    <%= f.password_field :password_confirmation, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit", class: " btn btn-lg btn-primary ">Create User</button>

  </div>

<% end %>

app/views/users/show.html.erb
<h2><%= @users.email %></h2><br>
<h1>Cette page est pour toi </h1>
<p>Cette page contient un lien vers la connaissance cosmique absolut</p><br>
<p>Le <a href="https://www.youtube.com/watch?v=DtKEQ0SZLv4">Christ cosmique</a> va tout t'expliquer</p><br>
<p>(Sinon la réponse à la question de l'univers est 42)</p><br>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>